### ISSUE TITLE
fetcher functions for useQuery and useMutation

### ISSUE THREAD

**Issue by Eliav2** [sinclairnick/trpc-react#1]
hey! thanks for this awesome repo,
you mentioned in the readme:

> 🔄 Useful helper methods like getting key, fetcher functions and prefetching exposed.

where is the fetcher function exposed? how can i use it?

related https://github.com/trpc/trpc/discussions/4638

thanks!

**Comment by sinclairnick** [comment]
You can directly call the underlying fetch call by using the `.$fetch()` method.

All non-hooks begin with the `$` symbol and can be used within and outside of react, enabling custom hooks etc.

i.e.
```
`// Call raw mutation. No affect on cache
trpc.some.procedure.$mutate(/* Input */);

// Call raw query. No affect on cache
trpc.some.procedure.$query(/* Input */); // <-- Fetcher function
```

**Comment by Eliav2** [comment]
thank you.
